# 公共配置文件
spring:
  application:
    name: code-generator
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    # todo 取消注释开启分布式 session（须先配置 Redis）
    # store-type: redis
    # 30 天过期
    timeout: 2592000
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/code_generator
    username: root
    password: 123456
  #   Redis 配置
  data:
    redis:
      database: 1
      host: localhost
      port: 6379
      timeout: 5000

  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
server:
  port: 8082
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: is_delete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）

# 对象存储
cos:
  client:
    SecretId: xxx
    SecretKey: xxx
    region: xxx
    bucket: xxx

# 接口文档配置
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.wang.codegenerator.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  openapi:
    title: "代码生成器接口文档"
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.wang.codegenerator.controller

# xxl-job 配置
xxl:
  job:
    admin:
      # xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
      addresses: http://localhost:8080/xxl-job-admin
    # xxl-job, access token
    accessToken: default_token
    executor:
      # xxl-job executor appname
      appname: generator-backend
      # xxl-job executor registry-address: default use address to registry , otherwise use ip:port if address is null
      address:
      # xxl-job executor server-info
      ip:
      port: 9999
      # xxl-job executor log-path
      logpath: logs/jobhandler
      # xxl-job executor log-retention-days
      logretentiondays: 30